### ISSUE TITLE
Typo on topo.md 

### ISSUE THREAD

**Issue by LifeIsStrange** [Oktosha/servo-image-benchmark#1]
"Write a bencmark which calls decode jpg function" benchmarck need a h :p
Thanks for your work.

**Comment by LifeIsStrange** [comment]
Same problem here "Write & compile sample bencmark" 

"Understand language feautures used in sample rust benchmark"
Features *

**Comment by Oktosha** [comment]
Thank you for be careful about typos, I'll fix them.

**Comment by LifeIsStrange** [comment]
Thanks !

**Comment by Oktosha** [comment]
Fixed.
